# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-15 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_auto_20170215_1134'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Remarks',
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_text',
            field=models.CharField(max_length=1000),
        ),
    ]
