# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-16 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0003_auto_20170215_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remarks',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='entry_text',
        ),
        migrations.AddField(
            model_name='entry',
            name='author',
            field=models.CharField(default='stephen king', max_length=200),
        ),
        migrations.AddField(
            model_name='entry',
            name='text',
            field=models.TextField(default='stephen king', max_length=1000),
        ),
        migrations.AddField(
            model_name='entry',
            name='title',
            field=models.CharField(default='twilight', max_length=200),
        ),
        migrations.AlterField(
            model_name='entry',
            name='pub_date',
            field=models.DateTimeField(verbose_name='blank=True, null=True'),
        ),
        migrations.DeleteModel(
            name='Remarks',
        ),
    ]
