# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_auto_20170216_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
    ]
