# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-19 09:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_remove_entry_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 19, 9, 33, 12, 682326, tzinfo=utc)),
        ),
    ]
