# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-20 16:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0008_auto_20170220_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 20, 16, 35, 46, 93131, tzinfo=utc)),
        ),
    ]
