# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-21 13:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0009_auto_20170220_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 2, 21, 13, 57, 10, 132856, tzinfo=utc)),
        ),
    ]
